# Generated by Django 5.1.6 on 2025-02-21 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('status', models.CharField(choices=[('Missing', 'Missing'), ('Found', 'Found'), ('Adopted', 'Adopted')], max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='dog_images/')),
            ],
        ),
        migrations.CreateModel(
            name='IssueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
            ],
        ),
    ]
