# Generated by Django 5.1.6 on 2025-02-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescue', '0004_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='phone',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='message',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.CharField(default='', max_length=150),
        ),
    ]
